@startuml
!pragma layout smetana
'https://plantuml.com/class-diagram

Class Main{
+ static void main()
}

Class User{
-String UserName
-String PassWord
-int Number
-String Mail
+Getter and Setters()
+String toString ()
}

Class Pet{
-String name
-int age
-String petType
-String description
+Getter and Setters()
+String toString ()
}

Class DbIo{

}

Class TextUI{

}

Class MainMenu{
+SetUp()
+signUp()
+logIn()
+makeUser()
+loadUser()
+saveUser()
+findUser()
}

Class PetOwner{
+makePet()
+loadPet()
+savePet()
+showUser()
+showPet()
+displayOptions()
+myPetInfo()
+seeMyPet()
+createPet()
+deletePet()
+myPetActivity()
+createActivity()
+activityHistory()
}

Class PetWalker{
+showJobs()
+jobHistory()
+showUser()
+displayOptions()
}

Main --* MainMenu
MainMenu --* User
User --* PetOwner
User --* PetWalker
PetOwner --* Pet
MainMenu --* TextUI
MainMenu --* DbIo
@enduml