@startuml
!pragma layout smetana
'https://plantuml.com/class-diagram

object Main
object MainMenu
object User
object PetOwner
object Pet
object PetWalker
object TextUI
object DbIo

Main --* MainMenu
MainMenu --* User : has a
MainMenu --* PetOwner : has a
MainMenu --* TextUI
MainMenu --* DbIo
PetOwner --* User : inherits
PetOwner --* Pet : has a
PetWalker --* User : inherits
@enduml